-- local luasnip = require("luasnip")
--
-- local snip = ls.snippet
-- local node = ls.snippet_node
-- local text = ls.text_node
-- local insert = ls.insert_node
-- local func = ls.function_node
-- local choice = ls.choice_node
-- local dynamicn = ls.dynamic_node
--
-- snip({
--     trig = "excom",
--     namr = "export default component",
--     dscr = "Export default component"
-- }, {
--     text("export default function "),
--     insert(1),
--     text("({ \n"),
--     insert(2),
--     text("\n}: {\n"),
--     insert(3),
--     text("\n}) {\n"),
--     insert(4),
--     text("\n}")
-- })
